services:
  personal-website:
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: personal-website

    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
