# Stage 1: Base
FROM node:20-alpine AS base
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Stage 2: Dependencies
FROM base AS deps
COPY package.json package-lock.json* ./
RUN npm ci

# Stage 3: Builder
FROM base AS builder
# Handle GITHUB_TOKEN for client-side bundling
ARG GITHUB_TOKEN
ARG VITE_GITHUB_TOKEN
ENV GITHUB_TOKEN=$GITHUB_TOKEN
ENV VITE_GITHUB_TOKEN=$GITHUB_TOKEN

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build the app (Vinxi will use the node-server preset from vite config)
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN npm run build

# Stage 4: Runner
FROM base AS runner
WORKDIR /app
ENV NODE_ENV production

# Security: Don't run as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 tanstack

# Only the .output folder is needed for the node-server preset
COPY --from=builder /app/.output ./.output

USER tanstack

# Set internal networking
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"
EXPOSE 3000

# Start using the entry point generated by the node-server preset
CMD ["node", ".output/server/index.mjs"]
